const express = require("express");
const { render } = require("express/lib/response");
const router = express.Router();
const clubcontroller = require("../controllers/clubcontroller");
router.get("/login", clubcontroller.clublogin);
router.post("/login", clubcontroller.loginsubmit);
router.post("/logout", clubcontroller.logout);
router.get("/", clubcontroller.clubview);
router.post("/addclubpost", clubcontroller.addclub);
router.post("/filterclub", clubcontroller.filterclub);
router.post("/deleteclub", clubcontroller.deleteclub);
router.post("/register", clubcontroller.signupentry);
router.get("/clubfilterender", clubcontroller.clubfilterender);
module.exports = router;
